apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-db-statefulset
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: sql-db
  template:
    metadata:
      labels:
        app: sql-db
    spec:
      containers:
      - name: sql-db
        image: mysql:8.0
        env:
        - name : MYSQL_ROOT_PASSWORD
          value : 'rootpassword'
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

